# Site settings
title: yqrashawn
SEOTitle: yqrashawn blog
header-img: img/home-bg.jpg
email: namy.19@gmail.com
description: "欢迎来到这里，看一个学生的成长"
keyword: "Sublime Text3,Github Pages,jekyll,Markdown,学生"
url: "http://rashawn.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     yqrashawn
github_username:    yqrashawn
#twitter_username:  yqrashawn
# facebook_username:  yqrashawn



# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: ra
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: rashawn.top



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "发牢骚。"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
#     {
#         title: "天镶的博客",
#         href: "http://lingyu.wang/"
#     },
 ]
